version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.16
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - xpack.security.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    expose:
      - "9200"
  db:
    image: postgres:11
    container_name: postgres
    environment:
      - POSTGRES_USER=fourfront_user
      - POSTGRES_PASSWORD=fourfront_password
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - "5432"

volumes:
  esdata:
    driver: local
  postgres_db:
    driver: local
